# Extra autostart processes
# exec-once = uwsm-app -- my-service
# exec-once = rclone mount obsidian:Obsidian ~/Documents/Vault --vfs-cache-mode full --daemon
exec-once = clipcascade
# exec-once = otd-daemon
